version: '3'
services:
  db:
    image: mysql:5.7.41
    networks:
      - voice-web
    container_name: db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=voiceweb
      - MYSQL_USER=voicecommons
      - MYSQL_PASSWORD=voicecommons
      - MYSQL_ROOT_PASSWORD=voicewebroot
    command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    ports:
      - 3306:3306
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    networks:
      - voice-web
  bundler:
    build:
      context: ./bundler
      dockerfile: Dockerfile
    container_name: bundler
    links:
      - db
      - redis
    volumes:
      - ./bundler:/home/node/code
    networks:
      - voice-web
    ports:
      - 9001:9001
    command: bash -c "npm ci && npm run build && npm start"
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: web
    links:
      - db
      - redis
      - supertokens
    volumes:
      - .:/code
      - audio_data:/code/web/public/audio
    environment:
      - DOTENV_CONFIG_PATH=/code/.env-local-docker
    networks:
      - voice-web
    ports:
      - 9000:9000
    command: bash -c "sed $$'s/\r$$//' /code/docker/wait-for-it.sh > /code/docker/wait-for-it.sh && /code/docker/wait-for-it.sh s3proxy:80 -- /code/docker/prepare_s3.sh && yarn --network-timeout 1000000 && yarn start"
  supertokens:
    container_name: supertokens
    image: registry.supertokens.io/supertokens/supertokens-mysql:9.0.2
    ports:
      - 3567:3567
    depends_on:
      - db
    environment:
      MYSQL_CONNECTION_URI: mysql://voicecommons:voicecommons@db:3306/voiceweb
    networks:
      - voice-web
    restart: unless-stopped
    healthcheck:
      test: >
        bash -c 'exec 3<>/dev/tcp/127.0.0.1/3567 && echo -e "GET /hello HTTP/1.1\r\nhost: 127.0.0.1:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  voice-web:

volumes:
  audio_data:
